[theme]
base = "dark"
primaryColor = "#4E88C7"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F2B"
textColor = "#E6EAF0"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false